import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import ThemeContainer from "../../components/ThemeContainer";
import ToggleThemeButton from "../../components/ToggleThemeButton";

export async function getStaticProps(context) {
  const id = context.params.id;
  try {
    const res = await fetch(`http://localhost:3000/api/movies/${id}`);
    const body = await res.json();

    return {
      props: {
        movie: body,
      },
    };
  } catch {
    return {
      props: {
        movie: null,
      },
    };
  }
}

export async function getStaticPaths() {
  const res = await fetch(`http://localhost:3000/api/movies`);
  const body = await res.json();

  const possiblePaths = body.map((movie) => {
    return { params: { id: movie.id } };
  });

  return {
    paths: possiblePaths,
    fallback: true,
  };
}

export default function MoviePage(props) {
  const router = useRouter();
  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  if (props.movie) {
    return (
      <ThemeContainer>
        <Head>
          <title>{props.movie.name} - Movies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="dark:bg-slate-800 bg-slate-100">
        <ToggleThemeButton />
          <h1 className="text-3xl dark:text-gray-100 text-slate-900">
            {props.movie.name}
          </h1>
          {/* <div className="w-52 rounded-xl aspect-[2/3]"> */}
          <img
            src={props.movie.poster}
            // width={200}
            // height={300}
            objectFit={"cover"}
            className="w-52 rounded-xl aspect-[2/3]"
          />
          {/* </div> */}
        </div>
      </ThemeContainer>
    );
  } else {
    return (
      <ThemeContainer>
        <h1>404 - Movie Doesn't Exist</h1>
      </ThemeContainer>
    );
  }
}
