import Head from "next/head";
import Image from "next/image";

// import allMovies from "./api/movies/allMovies";
import MovieList from "../components/MovieList";
import ToggleThemeButton from "../components/ToggleThemeButton";
import ThemeContainer from "../components/ThemeContainer";

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/movies");
  const body = await res.json();

  return {
    props: {
      allMovies: body,
    },
  };
}

export default function Home(props) {
  return (
    <ThemeContainer>
      <div className="p-0 m-0 bg-slate-100 dark:bg-slate-900">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="m-auto">
          <h1>DUMBFLIX</h1>
          <ToggleThemeButton />
          <div className="m-auto block w-auto">
            <MovieList
              list={props.allMovies}
              listTitle={
                "Recommended Recommended Recommended Recommended Recommended Recommended Recommended Recommended Recommended"
              }
            />
            <MovieList list={props.allMovies} listTitle={"Recommended"} />
          </div>
        </main>
      </div>
    </ThemeContainer>
  );
}
